SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
<<<<<<< HEAD
L1: DIV DOIS + 1
=======
L1: DIV DOIS
>>>>>>> 676241eca40d2c6232ab137c2fb669ebeafe6788
STORE NEW_DATA
MULT DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA , OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE 5
NEW_DATA: SPACE
TMP_DATA: SPACE
